version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./elise:/app/elise
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: mongo_server
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: elise
      MONGO_INITDB_ROOT_PASSWORD: elise_can_open_doors
      MONGO_INITDB_DATABASE: elise_db
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A elise.celery_worker worker --loglevel=info
    volumes:
      - ./elise:/app/elise
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
      - fastapi

volumes:
  redis_data:
  mongo_data:
